### ISSUE TITLE
NotificationListener接收到別的ScrollController的偏移通知。

### ISSUE THREAD

**Issue by std-c** [Fliggy-Mobile/frefresh#3]
如題：NotificationListener<ScrollNotification>

**Comment by chenBingX** [comment]
你好开发者，
可以提供更具体一些的例子吗？

**Comment by std-c** [comment]
> 你好开发者，
> 可以提供更具体一些的例子吗？

条件：集成 FRefresh/ GFCarousel 。  Container(Column[Other, FRefresh(ListView[GFCarousel, Other]]))。
现象： 当GFCarousel的banner图自动播放一次， FRefresh 就自动下拉一次。
